### ISSUE TITLE
Modloader support

### ISSUE THREAD

**Issue by CUexter** [antipatico/balatromobile#1]
I have identified that the basic patches only works when the balatro executable is unmodified. Can you try to add the hashes of the popular mod loader [Steamodded](https://github.com/Steamopollys/Steamodded) ?

**Comment by antipatico** [comment]
You can add the hashes yourself and open a PR, or set `supported_hashes = ["skip"]` as for example [the crt.toml patch does](https://github.com/antipatico/balatromobile/blob/91f887fcabcfb1d0691cd341865fc5b094968330/balatromobile/patches/crt.toml).

It would also be great to make the patcher smarter (E.G. force patching + manual patch enabling / disabling). Feel free to open a PR if you want to spend your time on it!

Otherwise, you can fork the source, patch it and run it locally :)

**Comment by antipatico** [comment]
For now, patch hashes are disabled. I am closing this issue. If you still have problems with mods, feel free to open another issue.
